zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - "2181:2181"
kafka:
  image: wurstmeister/kafka:0.8.2.0
  ports:
    - "9092:9092"
  links:
    - zookeeper:zk
  environment:
    KAFKA_ADVERTISED_HOST_NAME: 10.0.1.8
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
entitybatch:
  image: debezium-entity-batch-service
  links:
    - zookeeper:zookeeper
    - kafka:kafka
  environment:
    KAFKA: kafka:9092
    ZOOKEEPER: zookeeper:2181/